### ISSUE TITLE
How do I resolve a conflict?

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/GettingStarted#6]
git add!

**Comment by astrostubbs** [comment]
With tact and grace

**Comment by drphilmarshall** [comment]
Touche'

**Comment by drphilmarshall** [comment]
I 'm going to do some work on this one,  I think.

**Comment by karenyyng** [comment]
Does this refer to using the merge tool in git?

**Comment by drphilmarshall** [comment]
No - at least, my response will assume that the reader is using git on the
command line.

**Comment by karenyyng** [comment]
I should have shown the page for [git mergetool](http://git-scm.com/docs/git-mergetool) which is from the command line. I was not referring to a GUI. This command assumes that one of the following editors / editor commands to be used for comparing the difference of different commits though:
> emerge, gvimdiff, kdiff3, meld, vimdiff, and tortoisemerge

I do not feel comfortable collaborating people on the same branch on Git until I master this `git-mergetool` command. I don't want my collaborators to hate me for removing / messing up all their committed changes.

**Comment by drphilmarshall** [comment]
I see! Sounds good, Karen! If you want to try writing a little intro to
using `git mergetool`, please do go ahead and then submit a pull request.
Don't forget, you main audience is astronomers who are coming from `svn`,
and they prize brevity over almost everything else :-)

**Comment by karenyyng** [comment]
I tried my best to be concise while I wrote this [tutorial](https://gist.github.com/karenyyng/f19ff75c60f18b4b8149#concepts-for-resolving-git-conflicts). This may still be longer than what you want but feel free to extract what you need.

**Comment by drphilmarshall** [comment]
OK, still without mentioning `mergetool` I wrote two new FAQ in https://github.com/drphilmarshall/GettingStarted/commit/feec397ba77f62473a4c7aa672b3c7430aba76df - including notes on *not* forcing pushes. If and when I start using `mergetool` I may add another FAQ about that - but that can be a separate issue referring to this one. Also, pull requests are always welcome, if someone else wants to add something! :-)
